### PR TITLE
Fix/hybrid

### PR DESCRIPTION
**Pull request by reguly**
1. Fixes to the hybrid generation process - we don't have redundant code anymore.
2. Adding shared memory staging support for OP_INCs in C
@gihanmudalige could you please run the usual tests?

### CODE REVIEW

**Comment by gihanmudalige** [comment]
./reduction_mpi_cuda (i.e. on one process) fails with : 
src/cuda/op_cuda_rt_support.c(266) : cutilSafeCall() Runtime API error : an illegal memory access was encountered

I suppose this is due to the use of the hybrid code.

**Comment by reguly** [comment]
Ohhho, that was a really embarrassing bug in all the code generators (C and Fortran), where we didn’t set ind_inc or reduction to 1, if it was only the very first argument :) Pushed a fix.

**Comment by gihanmudalige** [comment]
Great, thanks. I am rerunning the tests again.

**Comment by gihanmudalige** [comment]
Ok. Tests all pass, you can merge.

**Comment by reguly** [comment]
Thank you Ghan!

**Pull request merged**
