### PR TITLE
Reordering over MPI

### PR DESCRIPTION
**Pull request by reguly**
as it says :) @gihanmudalige this is not called in current airfoil codes, as it would actually slow them down. Could you run the buildbot, just to make sure the backends compile okay?

### CODE REVIEW

**Comment by gihanmudalige** [comment]
Sorry .. I missed doing this. Let me run the tests now

**Comment by gihanmudalige** [comment]
OK .. tests passed. But do you want to add a unit test for the new functionality ?

**Comment by reguly** [comment]
Good point, I have added two tests to airfoil_hdf5. Please run them.

**Comment by gihanmudalige** [comment]
Apologies ... I will run the latest and approve this.

**Comment by reguly** [comment]
Have you been able to run the tests? Is this working okay?

**Comment by gihanmudalige** [comment]
Sorry not yet ... planing to do it today

**Pull request merged**
