### PR TITLE
Feature/f soa p8

### PR DESCRIPTION
**Pull request by reguly**
Adds SoA support to both C and Fortran backends (CUDA and OpenACC). Enabled with the OP_AUTO_SOA environment variable - needed for both code generation and execution.
Adds support for Power8.
@gihanmudalige could you please run the usual tests?

### CODE REVIEW

**Comment by gihanmudalige** [comment]
There is an issue in the Fortran applications where non-GPU parallelizations does not compile : 
input.o: In function `.C5_1107':
input.F90:(.data+0x130): undefined reference to `cudafor_'
airfoil_hdf5.o: In function `.STATICS1':
airfoil_hdf5.F90:(.data+0x4d8): undefined reference to `cudafor_'

I think the fix that is in master is a hack, where even non-GPU compilation lines use -Mcuda=cuda7.5,cc35

**Comment by reguly** [comment]
Thank you - I should have fixed it by introducing a new module path for CUDA-enabled modules. User apps will now have to first include that, then the one without /cuda at the end.

**Comment by reguly** [comment]
I have added a Fortran API (op_init_base) to avoid having to specify OP_MAPS_BASE_INDEX every time.

**Comment by gihanmudalige** [comment]
I am almost done with the tests. I think I manage to get cmake makefiles also working for now. It is I think due to a lack of some system libs.

**Comment by gihanmudalige** [comment]
The aero application's aero_mpi_cuda parallelization cannot select multiple GPUs anymore and requires the numawrap scrip to be specified. This is not an issue with this pull request, rather the changes that were done to the back-end some time ago. I think aero is not compatible with the current code generator due to the use of vector maps.

**Comment by gihanmudalige** [comment]
I think apart for the Aero application failing to select multiple GPUs without the numawrap script, this pull request is fine to be merged

**Comment by reguly** [comment]
Thank you!
One additional question, regarding auto SoA. Currently, the user needs to export OP_ATUO_SOA=1, which is being checked for by the code generator as well as the runtime. This however, might lead to a discrepancy between the two: at code generation time, we set it to 1, but at execution time it is not set. This will of course lead to incorrect results.

Should I therefore extend the code generator and the runtime, so that the generated _op.cpp file’s call to op_init will pass an additional argument, which enables the automatic conversion?

**Comment by gihanmudalige** [comment]
Could we just get the runtime to assume the value of OP_AUTO_SOA from the generated code ? I.e. if OP_AUTO_SOA was set to 1 during code generation time then the runtime assumes its 1, unless the user overrides it at runtime again with OP_AUTO_SOA=0. Is this difficult to do ?

**Comment by reguly** [comment]
That’s exactly what I am trying to do, and the way I propose is to append a parameter to op_init in the generated code. I don’t really know an other option that would guarantee that it gets set before datasets are uploaded to the GPU.

**Comment by gihanmudalige** [comment]
I see. OK so as the application developer does not need to worry about the modified op_init API (i.e. the modification is done by the code generator) then I think thats fine. Could you add this to the user docs as well if yo get a chance ?

**Comment by reguly** [comment]
Will do!

**Comment by gihanmudalige** [comment]
Just pushed in a minor addition to get aero_mpi_cuda working.

**Comment by reguly** [comment]
Thank you!
I have made the SoA API modifications and updated the docs. Please have a look, then I’ll merge.

**Comment by gihanmudalige** [comment]
This is fine. I think you can merge

**Comment by gihanmudalige** [comment]
The merge seems to have broken master now. I am getting NANs for airfoil_cuda and airfoil_mpi_cuda.

**Comment by reguly** [comment]
Which one? they seem to be running perfectly fine for me.

**Comment by gihanmudalige** [comment]
airfoil_cuda (both plan and hdf5) and airfoil_mpi_cuda. is giving NaNs. I am simply running and getting:

octon {master} ~/OP2-GIT/OP2-Common/apps/c/airfoil/airfoil_plain/dp$ ./airfoil_cuda 

 Initializing OP2
 Enabling Automatic AoS->SoA Conversion
 Using CUDA device: 0 Tesla K80
...
...
new execution plan #2 for kernel bres_calc
 number of blocks       = 7 
 number of block colors = 1 
 maximum block size     = 448 
 average thread colors  = 1.29 
 shared memory required =  38.56 KB
 average data reuse     = 1.18 
 data transfer (used)   = 0.40 MB 
 data transfer (total)  = 1.00 MB 
 SoA/AoS transfer ratio = 2.47 

 100        -nan 
 200        -nan 
 300        -nan 
 400        -nan 
 500        -nan 
 600        -nan 
 700        -nan 
 800        -nan 
 900        -nan 
 1000        -nan

**Comment by gihanmudalige** [comment]
It may be some issue with my local repo. Let me do a fresh clone and see.

**Comment by gihanmudalige** [comment]
I am afraid, I am still getting NaNs on Octon, even with a fresh clone of the repo. Any idea whts happening here ?

**Comment by gihanmudalige** [comment]
That fix to master seems to have resolved the issue. I am re-running tests now.

**Pull request merged**
