### PR TITLE
OpenMP 4 and fix of vectorised arguments

### PR DESCRIPTION
**Pull request by reguly**
This request pulls in OpenMP 4 support (singe process) as well as a fix to vectorised arguments

### CODE REVIEW

**Comment by gihanmudalige** [comment]
Does this mean that the Aero application is now working ? If so I can add it back to our tests.

**Comment by reguly** [comment]
Yes, it does. Though there are issues with Openacc and openmp, which I currently beleive to be compiler bugs...

**Comment by gihanmudalige** [comment]
Some initial errors: Code generating and compiling aero_hdf5 throws errors due to OP2_STRIDE not being defined.

**Comment by reguly** [comment]
Forgot to update aero_hdf5 - pushed in the fix for that.

**Comment by gihanmudalige** [comment]
Did you manage to compile this on Octon ? If so, what compilers/versions ?

**Comment by gihanmudalige** [comment]
Do we have any documentation on how to run OpenMP4 versions on GPUs ?
Any run-time flags involved ?

**Comment by reguly** [comment]
I can just compile and run airfoil_openmp4 without any settings or flags, on octon, using the source_clang file in my home.

**Comment by gihanmudalige** [comment]
All seem to work except airfoil_plain Fortran.  Surprisingly airfoil_hdf5 Fortran works.

**Comment by reguly** [comment]
Due to the fixed field width in fortran’s read (reading the set sizes) this will not work with any other size mesh… Restored so it works with 720k.

**Comment by gihanmudalige** [comment]
I am however getting : "GPU OpenMP runtime elided" Remarks - 
./res_calc_omp4kernel_func.cpp:23:11: remark: Offloading kernel to the GPU.
Combined construct detected.
GPU OpenMP runtime elided.
 [-Rpass-analysis]
  #pragma omp target teams distribute parallel for schedule(static,1)\
                  ^

**Comment by reguly** [comment]
Thanks Gihan! Those messages are expected!

**Comment by reguly** [comment]
I had to rebase this on the current master with loads of conflicts... Could you please re-run the checks to see that I haven't broken anything?

**Comment by gihanmudalige** [comment]
doing so now .. the major conflict was in op_gen_cuda_simple.py

**Comment by gihanmudalige** [comment]
Ok I think everything just passed. Can you have a look at  op_gen_cuda_simple.py  
This is the one that caused me a conflict and I had to do a merge with my local branch.

**Comment by reguly** [comment]
Moving over to fix/vectorised2

**Pull request closed without merging**
