### PR TITLE
Feature/translator pickup c defs

### PR DESCRIPTION
**Pull request by aowenson**
If an op_par_loop() statement contains a C macro definition where op2.py expects an integer, such as for the 'dim' field, then op2.py will fail to parse the code.

To address this, op2.py has been extended with logic that searches for such definitions, evaluates the RHS if it is an arithmetic expression (such as 1+3), and substitutes the RHS into the in-memory source code.

It can be argued that applying the C preprocessor would be better, however as the resulting source code would be very different to the input, then the user could not easily relate and syntax errors encountered by op2.py back to their source code.

### CODE REVIEW

**Comment by reguly** [comment]
Looks good, simple testing shows it works fine. How much work would it be to add support for evaluating expressions in the dim field of op_arg_dats? e.g. op_arg_dat(x, -1, OP_ID, 2*SOMEDEF, "double", OP_READ)

**Comment by aowenson** [comment]
If 'SOMEDEF' is a macro constant, and its definition is a numeric expression (for example "#define SOMEDEF 4"), then your request should already be supported. Are you finding that it is not?

Even something like "#define SOMEDEF 2*ANOTHER_DEF" should work, because the substitution is recursive.

**Comment by reguly** [comment]
Yes, SOMEDEF is something like #define SOMEDEF 2. The second case does work, but the first doesn’t seem to. In line 485 of op2.py I think you are only looking for perfect matches.

**Comment by aowenson** [comment]
Oh i see. This is easy to fix, I'll submit shortly

**Comment by reguly** [comment]
Looks good - please add the same for op_arg_dats as well around line 503. Currently only seems to do it for op_decl_consts

**Comment by reguly** [comment]
Hmm, something is still not working. In airfoil.cpp, I add:
#define PDIM 2
and I swap
op_arg_dat(p_res,0,pecell,4,"double",OP_INC),
to
op_arg_dat(p_res,0,pecell,2*PDIM,"double",OP_INC),

but in the generated airfoil_op.cpp it comes out as
op_arg_dat(p_res,0,pecell,2,"double",OP_INC),

**Pull request merged**
