### PR TITLE
Fix/codeformatting

### PR DESCRIPTION
**Pull request by gihanmudalige**
Uses clang-format to apply the coding guidelines for the source code in the back-end libraries  and the generated code. clang-format has been integrated into the code generators so that any generated code is formatted at code-gen time (if clang-format is in the PATH). 

There is also some other minor fixes that were discovered during this exercise, such as fixing the reduction applications's vec and openmp parallelizations.

### CODE REVIEW

**Comment by gihanmudalige** [comment]
Istvan, could you have a look and let me know if this is ok. I think clang-format is very useful to generate good readable code. The OP2 wiki has a coding guide, which we never managed to adhere to. However I think clang-format automates this process.

**Comment by reguly** [comment]
Looks good! Seems to work fine when it’s not found too. My concern is that it will re-indent the user’s files as well, which may not be good. Can it be done just for *kenel.cpp, etc. files?

**Comment by gihanmudalige** [comment]
It can certainly be done only for *kernle.cpp files. There is a small shell script format.sh under the translator//c/python/ folder which does the formatting. Let me have a look.

**Comment by gihanmudalige** [comment]
@reguly Would it be ok to merge ?

**Comment by reguly** [comment]
Looks good, though I haven't tested it as I am out running errands, but go ahead and merge it.

**Pull request merged**
